repos:
  # Ruff - linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]  # automatically fix issues
      - id: ruff-format  # format code

  # mypy - static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy

  # Built-in file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace    # remove trailing spaces
      - id: end-of-file-fixer     # ensure files end with newline

  # pytest with 100% coverage requirement
  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest with 100% coverage
        entry: poetry run pytest --cov=src --cov-fail-under=100 --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
