name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    name: pre-commit (lint/format/tests)
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Enable in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Cache Poetry venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.py.outputs.python-version || '3.12' }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-interaction

      # This runs all hooks defined in pre-commit (e.g., ruff, pytest, mypy)
      - name: Run pre-commit on all files
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files

  # === Optional: separate pytest job (keep if you want tests isolated) ===
  tests:
    name: pytest (separated)
    runs-on: ubuntu-latest
    needs: precommit
    if: >
      github.event_name != 'push' || github.ref == 'refs/heads/main'
      # If you already run pytest in pre-commit, you can disable this whole job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Enable in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Cache Poetry venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.py.outputs.python-version || '3.12' }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pytest (with coverage)
        run: |
          poetry run pytest -q --maxfail=1 --disable-warnings \
            --cov=src --cov-report=xml --junitxml=pytest-junit.xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-junit
          path: pytest-junit.xml
          if-no-files-found: ignore
